apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    kubernetes.io/app: web2
  name: web2
  namespace: web
spec:
  containers:
  - image: httpd
    name: web2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
