apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  storageClassName: "" # Pusta storage class musi być wpisana bo inaczej defaultowa storage class będzie uzyta (jeśli nie ma jej to jest issue)
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  hostPath:
    path: "/files"
