apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-htpasswd
  namespace: app1
type: Opaque
data:
  .htpasswd: bWFyaW9sYTokYXByMSRkUWN1aXpzaiQzUXphU3ZVcnhTRS85UmQzYWxyZzQvCg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: app1
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }
    http {
        server {
            listen       80;
            listen  [::]:80;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            auth_basic "Secure Site";
            auth_basic_user_file conf/.htpasswd;
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: app1
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx
    - name: htpasswd-volume
      mountPath: /etc/nginx/conf
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config
  - name: htpasswd-volume
    secret:
      secretName: nginx-htpasswd
