apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  storageClassName: "" # Pusta storage class musi być wpisana bo inaczej defaultowa storage class będzie uzyta (jeśli nie ma jej to jest issue)
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/files"
