# Default values for simple-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  name: simple-app-demo

replicaCount: 1

image:
  name: nginx
  pullPolicy: IfNotPresent
  tag: "1.19.1"

service:
  type: ClusterIP

ingress:
  className: "nginx"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
