apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    kubernetes.io/app: simple-app
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      kubernetes.io/app: simple-app
  template:
    metadata:
      labels:
        kubernetes.io/app: simple-app
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80 
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx
          - name: htpasswd-volume
            mountPath: /etc/nginx/conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
        - name: htpasswd-volume
          secret:
            secretName: nginx-htpasswd
