apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-ingress
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: simple-app.192.168.1.100.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-app-svc 
                port:
                  number: 80
